#!/bin/bash

# 寻找 svn 两个版本号间被改动和新增的文件

# terminal color
    red=$'\e[1;31m'
  green=$'\e[1;32m'
 yellow=$'\e[1;33m'
   blue=$'\e[1;34m'
magenta=$'\e[1;35m'
   cyan=$'\e[1;36m'
  white=$'\e[1;37m'
 normal=$'\e[m'

function show_usage()
{
    echo "${cyan}-----USAGE----${normal}"
    echo "$0 rold:rnew             ${red}find sick file for OP.${normal}"
}

if [ $# -lt 1 ];then
    show_usage
    exit 1
fi

svn diff -r $1 | awk '{if ("+++" == $1){ print $2} }'

